name: Deploy to Github Pages

on:
  push:
    branches:
      - main  # You can add more branches here if needed

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Updated to the latest version

      - name: Use Node.js
        uses: actions/setup-node@v4  # Updated to the latest version
        with:
          node-version: 'lts*'  # Uses the latest Long-Term Support (LTS) version

      - name: Install dependencies
        run: npm install  # Simplified command

      - name: Build for deployment
        run: next build  # Uses the recommended Next.js build command (replaces deprecated `npm run build`)

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_SECRET_KEY }}
          publish_dir: ./out  # No changes here